[package]
name = "chapter4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_cmd = "2.0.7"
clap = "4.0.29"
predicates = "2.1.4"
ran = "1.0.7"
rand = "0.8.5"
